name: "CI - Build and Test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NET_VERSION: '10.0.201'

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.NET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build Core and CLI projects
        run: |
          dotnet build RayTracer.Core/RayTracer.Core.csproj --no-restore -c Release
          dotnet build RayTracer.Cli/RayTracer.Cli.csproj --no-restore -c Release

      - name: Run unit tests
        run: dotnet test RayTracer.Core.Tests/RayTracer.Core.Tests.csproj --no-build -c Release --verbosity minimal
